version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - prealloc

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  misspell:
    locale: US
  errcheck:
    check-type-assertions: true
    check-blank: true

formatters-settings:
  goimports:
    local-prefixes:
      - github.com/Laminar-Bot/birdeye-go

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
