version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - prealloc
  settings:
    misspell:
      locale: US
    errcheck:
      check-type-assertions: false
      check-blank: false

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/Laminar-Bot/birdeye-go

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
